### ISSUE TITLE
Test console.log

### ISSUE THREAD

**Issue by hdrdavies** [fcscripters/Wordpi#43]
Some comments / console.logs that would improve your badges if removed! +1 

https://github.com/fcscripters/Wordpi/blob/master/test/test.js#L16
https://github.com/fcscripters/Wordpi/blob/master/test/test.js#L22
https://github.com/fcscripters/Wordpi/blob/master/test/test.js#L29
https://github.com/fcscripters/Wordpi/blob/master/test/test.js#L37
https://github.com/fcscripters/Wordpi/blob/master/test/test.js#L65

**Comment by Conorc1000** [comment]
All done thanks
